app:
  name: "answersuck-backend"
  version: "0.0.2"

web:
  url: "http://localhost:8000"

http:
  port: "8080"

logger:
  logLevel: "debug"

postgres:
  poolMax: 2
  simpleProtocol: true # see pgx.ConnConfig.PreferSimpleProtocol

cache:
  expiration: 1h
  db: 0

session:
  expiration: 4h
  cookieName: "id"
  cookieSecure: false
  cookieHttpOnly: true
  cookiePath: "/v1"

securityToken:
  expiration: 1m
  signingKey: "secret"

password:
  resetTokenExpiration: 10m

smtp:
  host: "smtp.yandex.ru"
  port: 465

fileStorage:
  endpoint: "s3.storage.selcloud.ru"
  bucket: "answersuck"
  ssl: true

  # if true FILE_STORAGE_CDN_DOMAIN env must be set,
  # otherwise using FILE_STORAGE_DOMAIN env for generating uploaded file url
  cdn: false

email:
  templates:
    accountVerification: "./web/account_verification.html"
    accountPasswordReset: "./web/account_password_reset.html"
  subjects:
    accountVerification: "Подтверждение аккаунта"
    accountPasswordReset: "Сброс пароля"
  formats:
    accountVerification: "%s/verify?code=%s"
    accountPasswordReset: "%s/reset?token=%s"
